spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${common.local-ip}:3306/directhouse?serverTimezone=UTC
    username: user1
    password: password
  web:
    server:
      port: 80803
  main:
    allow-bean-definition-overriding: false
  devtools:
    restart:
      enabled: false
      additional-paths: classpath:/
    livereload:
      enabled: true
    thymeleaf:
      cache: false


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
          #header: Authorization
          #silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret라는 문자열을 BASE64로 인코딩한 거
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQ
  token-validity-in-seconds: 86400 #초

common:
  local-ip: localhost