spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${common.local-ip}:3306/{DB이름}?serverTimezone=UTC
    username: u
    password: u
  web:
    server:
      port: 8080
  main:
    allow-bean-definition-overriding: false
  devtools:
    restart:
      enabled: false
      additional-paths: classpath:/
    livereload:
      enabled: true
    thymeleaf:
      cache: false


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          #header: Authorization
          #silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret라는 문자열을 BASE64로 인코딩한 거
          secret:
          token-validity-in-seconds: 86400 #초

common:
  local-ip: localhost