server:
  port: 8080
  servlet:
    session:
      timeout: 600s
      persistent: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:
    username:
    password:

  main:
    allow-bean-definition-overriding: false
  devtools:
    restart:
      enabled: false
      additional-paths: classpath:/
    livereload:
      enabled: true
    thymeleaf:
      cache: false


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
security:
  jwt:
    #header: Authorization

    secret:
    token-validity-in-seconds: 86400 #초
clova:
  api:
    url:
    api-key:
    request-id:
    task-id:
common:
  local-ip: localhost